library(metaseqr)

data("mm9.gene.data",package="metaseqr")

out <- metaseqr(
	counts=mm9.gene.counts,
	sample.list=sample.list.mm9,
	contrast=c("e14.5_vs_adult_8_weeks"),
	libsize.list=libsize.list.mm9,
	id.col=4,
	annotation="fixed",
	org="mm9",
	count.type="gene",
	normalization="edaseq",
	statistics="deseq",
	pcut=0.05,
	fig.format="x11",
	export.what=c("annotation","p.value","adj.p.value","fold.change"),
	export.scale=c("natural","log2"),
	export.values="normalized",
	export.stats=c("mean","sd","cv"),
	gene.filters=list(
		length=list(
			length=500
		),
		avg.reads=list(
			average.per.bp=100,
			quantile=0.25
		),
		expression=list(
			median=TRUE,
			mean=FALSE,
			quantile=NA,
			known=NA
		),
		biotype=get.defaults("biotype.filter","mm9")
	),
	out.list=TRUE
)
